# Generated by Django 5.0.3 on 2024-03-24 22:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_with_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('expert', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='experts/')),
                ('phone_number', models.TextField(max_length=15)),
                ('telegram', models.URLField(validators=[django.core.validators.RegexValidator('^https?:\\/\\/t\\.me\\/[a-zA-Z0-9_-]{5,}$')])),
                ('instagram', models.URLField(validators=[django.core.validators.RegexValidator('^https?:\\/\\/www\\.instagram\\.com\\/[a-zA-Z0-9_-]{5,}$')])),
                ('facebook', models.URLField(validators=[django.core.validators.RegexValidator('^https?:\\/\\/www\\.facebook\\.com\\/[a-zA-Z0-9_-]{5,}$')])),
                ('vkontakte', models.URLField(validators=[django.core.validators.RegexValidator('^https?:\\/\\/vk\\.com\\/[a-zA-Z0-9_-]{5,}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('parameters', models.TextField(default='', null=True)),
                ('price', models.FloatField(max_length=12, null=True)),
                ('reviews', models.TextField(default='', null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_for_dip.category')),
            ],
        ),
    ]
