# Generated by Django 5.0.3 on 2024-03-31 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_for_dip', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='********', max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, default='********', max_length=255, null=True)),
                ('address', models.CharField(blank=True, default='********', max_length=255, null=True)),
                ('job', models.CharField(blank=True, default='********', max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=' profiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
