# Generated by Django 5.0.3 on 2024-03-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_for_dip', '0002_product_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parameters',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='reviews',
            field=models.TextField(default='', null=True),
        ),
    ]
